blog/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# Author:Yanxin Zhang
from django.conf.urls import url
from . import views
from .feeds import LatestPostFeed
urlpatterns = [
    url(r'^$',views.post_list,name='post_list'),
    #url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,name='post_detail'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,name='post_list_by_tag'),
    url(r'^feed/$',LatestPostFeed(),name='post_feed'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
sitemaps = {'posts': PostSitemap,}


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',include('blog.urls',namespace='blog')),
    ##这告诉Django在客户端访问时建立一个站点地图/sitemap.xml。
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
##这个管理器允许你对post对象添加获取删除标签
from taggit.managers import TaggableManager
# Create your models here.

####定义管理器方法是Django自带的
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status='published')
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )
    title = models.CharField(max_length=200)
####   重点slug看似没用但是他将来将会在URL中使用url的帖子返回一个相对地址
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title
    #####管理器objects 为默认的,published为我们创建的这样我们就可以用published管理器了
    ###Post.published.filter而不是post.objects
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
#####创建一个评论系统
class Comment(models.Model):
    name = models.CharField(max_length=25)
    body = models.TextField()
    post = models.ForeignKey(Post,related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    ###用来自动过滤不好的评论
    activate = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from .models import Comment
from django import forms
class CommentForm(forms.ModelForm):
    class Meta:
        ####通过模型创建表单
        model = Comment
        fields =('name','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Comment
from .forms import CommentForm
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count
# Create your views here.
####视图带有一个可选的tag_slug参数默认为none
def post_list(request,tag_slug=None):
    ####获取对象将其分页,每页展示多少内容和有多少页
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        #####用给定的slug来获取标签对象
        tag = get_object_or_404(Tag,slug=tag_slug)
        ######过滤所有帖子只留下给定标签的帖子
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list,5)
    page = request.GET.get('page')
    try:
        ###通过paginator的page方法在期望的页面中获取对象
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'page': page,'tag': tag}
    return render(request,'blog/post_list.html',context)
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    #####获取所有有效评论并
    comments = post.comments.filter(activate=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        ####如果评论有效生成新的评论但不保存倒数据库
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            ##我们为我们刚创建的帖子分配一个评论
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
        ####values_list() 查询集返回包含给定的字段值的元祖。
        ## 我们传给元祖flat=True来获取一个简单的列表类似[1,2,3,...]。
        post_tags_ids = post.tags.values_list('id',flat=True)
        similar_posts =Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
        similar_posts =similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    context ={'post': post,'comments':comments,'comment_form':comment_form,
              'new_comment':new_comment,'similar_posts':similar_posts}

    return render(request,
                  'blog/post_detail.html',
                  context)
####使post_list视图转变为一个基于类的视图
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post_list.html'

blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <div class="header-container" style="background: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url
    ('https://foofish.net/images/peitu/daniela-cuevas-21225.jpg'); background-position: center; background-size: cover;
    "></div>

</head>
<body>
 <div id="content">
      {% block content %}
      {% endblock %}
     </div>
  <div id="sidebar">
      <h2>人生苦短,Python当歌</h2>
        <p>总计 {% total_posts %} 条博客.</p>
       <p><a href="{% url "blog:post_feed" %}">RSS</a> </p>
      <h3>最新文章</h3>
        {% show_latest_posts 3 %}
      <h3>评论最多</h3>
      <!--没有下面这句话不会运行,因为没有存储模版标签-->
      {% get_most_commented_posts as most_commented_posts %}
      <ul>
          {% for post in most_commented_posts %}

      <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
      {% endfor %}
          </ul>
  </div>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}


<h2>Similar posts</h2>
{% for post in similar_posts %}
<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
{% empty %}
 There are no similar post.
{% endfor %}
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment {{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments have been add yet.</p>
{% endfor %}
{% if new_comment %}
  <h2>Your comments have been added.</h2>
{% else %}
<h2>Add a new comment.</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
{% endblock %}

blog/templates/blog/post_latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title  %}zyx{% endblock %}
{% block content %}
  <h1>人生苦短,Python当歌</h1>
  </a>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>


<p class="tags">
  Tags:
  {% for tag in post.tags.all %}
  <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
  {% if not forloop.last %}, {% endif %}
  {% endfor %}
</p>
     <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
    <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
  {% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
          <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
          <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>